apiVersion: v1
kind: Pod
metadata:
  name: pod configmap
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom: #attaching the configmap file
        - configMapRef:
            name: myconfig